### ISSUE TITLE
Betterify CSS

### ISSUE THREAD

**Issue by ozeliurs** [2019-2020-ps6/2022-2023-ps6-webonjour#199]
- [x] Homepage
- [x] Quiz Selection
- [x] Quiz Answer (needs #180 merge)
- [x] Quiz Reorder
- [x] Clue
- [x] Learning Card (needs #180 merge)
- [x] Results (needs #180 merge)
